// <auto-generated />
using System;
using LionDev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240409111917_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LionDev.Models.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeLosMasBuscados")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = new Guid("708e9934-c409-406f-9372-d990e36c6e16"),
                            Cantidad = 15,
                            Color = "Negro",
                            Descripcion = "Buso saco rick and morty fuck",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buso saco rick and morty fuck",
                            ParaSexo = "Masculino",
                            Referencia = "BSRAMF",
                            Talla = "14",
                            UrlImagen = "../../../../assets/ProductosImagenes/buso-saco-rick-and-morty-fuck.png",
                            Valor = 140000
                        },
                        new
                        {
                            IdProducto = new Guid("f1bb9445-1d57-43e0-81e3-3e6d153d717f"),
                            Cantidad = 25,
                            Color = "Negro",
                            Descripcion = "Sudadera clásica nautica",
                            EsDeLosMasBuscados = true,
                            Nombre = "Sudadera clásica nautica",
                            ParaSexo = "Masculino",
                            Referencia = "SC",
                            Talla = "15",
                            UrlImagen = "../../../../assets/ProductosImagenes/sudadera-clasica-nautica.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("a7fc3a86-a6ec-4792-adea-ce3b423a33fe"),
                            Cantidad = 35,
                            Color = "Negro",
                            Descripcion = "Buzo de compresión en licra protección UV",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buzo compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "BCL",
                            Talla = "5",
                            UrlImagen = "../../../../assets/ProductosImagenes/buzo-compresio-licra.png",
                            Valor = 3000
                        },
                        new
                        {
                            IdProducto = new Guid("b3bf81b2-dd8d-47c1-8032-262dd1f6c351"),
                            Cantidad = 19,
                            Color = "negro y colores en el centro",
                            Descripcion = "Buzo saco anime one piece",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buzo saco anime",
                            ParaSexo = "masculino",
                            Referencia = "BSA",
                            Talla = "14",
                            UrlImagen = "../../../../assets/ProductosImagenes/buzo-saco-anime.png",
                            Valor = 35000
                        },
                        new
                        {
                            IdProducto = new Guid("f986b47b-89b5-417f-95dc-d78769570ca1"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Camiseta corta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta compresión licra",
                            ParaSexo = "Femenino",
                            Referencia = "CCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/ProductosImagenes/buzo-saco-anime.png",
                            Valor = 45000
                        },
                        new
                        {
                            IdProducto = new Guid("d72fb25b-fa90-4e13-80bf-fa0a6ae0afc2"),
                            Cantidad = 85,
                            Color = "Blanco",
                            Descripcion = "Camiseta compresión licra UV slim",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "CCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/ProductosImagenes/buzo-saco-anime.png",
                            Valor = 45000
                        },
                        new
                        {
                            IdProducto = new Guid("7eee4293-49b3-492b-9897-59b7b83abc50"),
                            Cantidad = 87,
                            Color = "Blanco",
                            Descripcion = "Pantalon compresión licra",
                            EsDeLosMasBuscados = true,
                            Nombre = "Pantalon compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "PCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/ProductosImagenes/pantalon-compresion-licra.png",
                            Valor = 48000
                        },
                        new
                        {
                            IdProducto = new Guid("1340af74-4422-4068-930e-a013c205c5f2"),
                            Cantidad = 87,
                            Color = "Varios colores",
                            Descripcion = "Medias veladas termicas mujer efecto piel",
                            EsDeLosMasBuscados = true,
                            Nombre = "Medias veladas térmicas",
                            ParaSexo = "Femenino",
                            Referencia = "MVT",
                            Talla = "17",
                            UrlImagen = "../../../../assets/ProductosImagenes/medias-veladas-termicas.png",
                            Valor = 48000
                        },
                        new
                        {
                            IdProducto = new Guid("26ea0ca2-e2e1-400f-94cb-7c8e444b2f82"),
                            Cantidad = 65,
                            Color = "Varios colores",
                            Descripcion = "Medias antideslizantes yoga pilates fitnics",
                            EsDeLosMasBuscados = true,
                            Nombre = "Medias antideslizantes",
                            ParaSexo = "Femenino",
                            Referencia = "MA",
                            Talla = "15",
                            UrlImagen = "../../../../assets/ProductosImagenes/medias-antideslizantes-yoga-pilates.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("bafcb817-ae03-4c3c-9119-b8b98027177b"),
                            Cantidad = 28,
                            Color = "Rojo",
                            Descripcion = "Uniforme mujer antifluido scrub",
                            EsDeLosMasBuscados = true,
                            Nombre = "Uniforme mujer antifluido",
                            ParaSexo = "Femenino",
                            Referencia = "UMA",
                            Talla = "95",
                            UrlImagen = "../../../../assets/ProductosImagenes/uniforme-mujer-antifluido.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("5cff3790-34eb-4039-bac1-9002691622df"),
                            Cantidad = 25,
                            Color = "Blanco y negro",
                            Descripcion = "Sudadera camuflada reforzada en tela náutica",
                            EsDeLosMasBuscados = true,
                            Nombre = "Vestido corto juvenil",
                            ParaSexo = "Femenino",
                            Referencia = "SCR",
                            Talla = "95",
                            UrlImagen = "../../../../assets/ProductosImagenes/vestido-corto-juvenil.png",
                            Valor = 85000
                        });
                });

            modelBuilder.Entity("LionDev.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDeDocumento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("16430be5-b976-4403-be9c-0fd9e6f81bc2"),
                            Apellidos = "Falcao",
                            Contrasena = "Rada1",
                            CorreoElectronico = "rada@gmail.com",
                            Direccion = "Calle 1",
                            Genero = "Masculino",
                            Nombres = "Radamel",
                            NumeroDeDocumento = "12345",
                            Rol = "Comprador",
                            TipoDeDocumento = "Cedula"
                        },
                        new
                        {
                            IdUsuario = new Guid("8ea02594-77a1-481f-a565-1d6ead77bc1d"),
                            Apellidos = "Rodriguez",
                            Contrasena = "James1",
                            CorreoElectronico = "james@gmail.com",
                            Direccion = "Calle 2",
                            Genero = "Masculino",
                            Nombres = "James",
                            NumeroDeDocumento = "12346",
                            Rol = "Administrador",
                            TipoDeDocumento = "Cedula"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
