// <auto-generated />
using System;
using LionDev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229161302_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LionDev.Models.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeLosMasBuscados")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = new Guid("655360b2-9b43-4119-ba75-6791e2782e5a"),
                            Cantidad = 15,
                            Color = "Negro",
                            Descripcion = "Chaqueta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Chaqueta",
                            ParaSexo = "Masculino",
                            Referencia = "C3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/C3.png",
                            Valor = 140000
                        },
                        new
                        {
                            IdProducto = new Guid("2dec61e1-bdf2-4812-9b7f-629981f445fb"),
                            Cantidad = 15,
                            Color = "Blanco y rojo",
                            Descripcion = "Falda larga",
                            EsDeLosMasBuscados = true,
                            Nombre = "Falda larga",
                            ParaSexo = "Femenino",
                            Referencia = "FL3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/FL3.png",
                            Valor = 35000
                        },
                        new
                        {
                            IdProducto = new Guid("35c9fe8f-5419-495a-bbfe-22473b3cea4b"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Camiseta corta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta",
                            ParaSexo = "Femenino",
                            Referencia = "CA5",
                            Talla = "16",
                            UrlImagen = "ProductosImagenes/CA5.png",
                            Valor = 45000
                        });
                });

            modelBuilder.Entity("LionDev.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDeDocumento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("5630ff27-8c29-407c-9263-e35be20c634c"),
                            Apellidos = "Falcao",
                            Contrasena = "Rada1",
                            CorreoElectronico = "rada@gmail.com",
                            Direccion = "Calle 1",
                            Genero = "Masculino",
                            Nombres = "Radamel",
                            NumeroDeDocumento = "12345",
                            Rol = "Comprador",
                            TipoDeDocumento = "Cedula"
                        },
                        new
                        {
                            IdUsuario = new Guid("5d1d4802-13c3-4c72-8d73-70d104af9af2"),
                            Apellidos = "Rodriguez",
                            Contrasena = "James1",
                            CorreoElectronico = "james@gmail.com",
                            Direccion = "Calle 2",
                            Genero = "Masculino",
                            Nombres = "James",
                            NumeroDeDocumento = "12346",
                            Rol = "Administrador",
                            TipoDeDocumento = "Cedula"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
