// <auto-generated />
using System;
using LionDev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LionDev.Models.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeLosMasBuscados")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = new Guid("787c05f4-48b2-43d6-a88c-25c20c0a60d4"),
                            Cantidad = 15,
                            Color = "Negro",
                            Descripcion = "Buso saco rick and morty fuck",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buso saco rick and morty fuck",
                            ParaSexo = "Masculino",
                            Referencia = "BSRAMF",
                            Talla = "14",
                            UrlImagen = "../../../../assets/buso-saco-rick-and-morty-fuck.png",
                            Valor = 140000
                        },
                        new
                        {
                            IdProducto = new Guid("dfd7e68b-3734-4b18-9559-c757092706ac"),
                            Cantidad = 25,
                            Color = "Negro",
                            Descripcion = "Sudadera clásica nautica",
                            EsDeLosMasBuscados = true,
                            Nombre = "Sudadera clásica nautica",
                            ParaSexo = "Masculino",
                            Referencia = "SC",
                            Talla = "15",
                            UrlImagen = "../../../../assets/sudadera-clasica-nautica.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("84d2d2cd-1623-433d-9b04-b3a0f6a241fd"),
                            Cantidad = 35,
                            Color = "Negro",
                            Descripcion = "Buzo de compresión en licra protección UV",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buzo compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "BCL",
                            Talla = "5",
                            UrlImagen = "../../../../assets/buzo-compresio-licra.png",
                            Valor = 3000
                        },
                        new
                        {
                            IdProducto = new Guid("85b0f514-ec57-4494-8a0d-2a90ef685f2f"),
                            Cantidad = 19,
                            Color = "negro y colores en el centro",
                            Descripcion = "Buzo saco anime one piece",
                            EsDeLosMasBuscados = true,
                            Nombre = "Buzo saco anime",
                            ParaSexo = "masculino",
                            Referencia = "BSA",
                            Talla = "14",
                            UrlImagen = "../../../../assets/buzo-saco-anime.png",
                            Valor = 35000
                        },
                        new
                        {
                            IdProducto = new Guid("4285a1a3-be4b-47cb-ab4b-ad3049cea3e7"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Camiseta corta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta compresión licra",
                            ParaSexo = "Femenino",
                            Referencia = "CCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/buzo-saco-anime.png",
                            Valor = 45000
                        },
                        new
                        {
                            IdProducto = new Guid("da28b8eb-b853-4bd9-90cf-c855b2eda97d"),
                            Cantidad = 85,
                            Color = "Blanco",
                            Descripcion = "Camiseta compresión licra UV slim",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "CCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/buzo-saco-anime.png",
                            Valor = 45000
                        },
                        new
                        {
                            IdProducto = new Guid("a252b2d7-52cf-46bf-b813-17545ff78de5"),
                            Cantidad = 87,
                            Color = "Blanco",
                            Descripcion = "Pantalon compresión licra",
                            EsDeLosMasBuscados = true,
                            Nombre = "Pantalon compresión licra",
                            ParaSexo = "Masculino",
                            Referencia = "PCL",
                            Talla = "16",
                            UrlImagen = "../../../../assets/pantalon-compresion-licra.png",
                            Valor = 48000
                        },
                        new
                        {
                            IdProducto = new Guid("8ed07524-6dc2-49df-b5a5-aba35a67e19e"),
                            Cantidad = 87,
                            Color = "Varios colores",
                            Descripcion = "Medias veladas termicas mujer efecto piel",
                            EsDeLosMasBuscados = true,
                            Nombre = "Medias veladas térmicas",
                            ParaSexo = "Femenino",
                            Referencia = "MVT",
                            Talla = "17",
                            UrlImagen = "../../../../assets/medias-veladas-termicas.png",
                            Valor = 48000
                        },
                        new
                        {
                            IdProducto = new Guid("14792c94-c0d0-4f8e-b18d-60364cc9655e"),
                            Cantidad = 65,
                            Color = "Varios colores",
                            Descripcion = "Medias antideslizantes yoga pilates fitnics",
                            EsDeLosMasBuscados = true,
                            Nombre = "Medias antideslizantes",
                            ParaSexo = "Femenino",
                            Referencia = "MA",
                            Talla = "15",
                            UrlImagen = "../../../../assets/medias-antideslizantes-yoga-pilates.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("fc72f1e5-9d9c-4fac-b0b8-efc6fabacd32"),
                            Cantidad = 28,
                            Color = "Rojo",
                            Descripcion = "Uniforme mujer antifluido scrub",
                            EsDeLosMasBuscados = true,
                            Nombre = "Uniforme mujer antifluido",
                            ParaSexo = "Femenino",
                            Referencia = "UMA",
                            Talla = "95",
                            UrlImagen = "../../../../assets/uniforme-mujer-antifluido.png",
                            Valor = 145000
                        },
                        new
                        {
                            IdProducto = new Guid("6daa735b-a825-4049-bc3f-076692e57660"),
                            Cantidad = 25,
                            Color = "Blanco y negro",
                            Descripcion = "Sudadera camuflada reforzada en tela náutica",
                            EsDeLosMasBuscados = true,
                            Nombre = "Vestido corto juvenil",
                            ParaSexo = "Femenino",
                            Referencia = "SCR",
                            Talla = "95",
                            UrlImagen = "../../../../assets/vestido-corto-juvenil.png",
                            Valor = 85000
                        });
                });

            modelBuilder.Entity("LionDev.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDeDocumento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("b56cd5a2-6ded-4284-818a-2b5a1952667e"),
                            Apellidos = "Falcao",
                            Contrasena = "Rada1",
                            CorreoElectronico = "rada@gmail.com",
                            Direccion = "Calle 1",
                            Genero = "Masculino",
                            Nombres = "Radamel",
                            NumeroDeDocumento = "12345",
                            Rol = "Comprador",
                            TipoDeDocumento = "Cedula"
                        },
                        new
                        {
                            IdUsuario = new Guid("d2f46a3e-7783-4590-8564-8979f0bba1d3"),
                            Apellidos = "Rodriguez",
                            Contrasena = "James1",
                            CorreoElectronico = "james@gmail.com",
                            Direccion = "Calle 2",
                            Genero = "Masculino",
                            Nombres = "James",
                            NumeroDeDocumento = "12346",
                            Rol = "Administrador",
                            TipoDeDocumento = "Cedula"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
