// <auto-generated />
using System;
using LionDev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LionDev.Models.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeLosMasBuscados")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = new Guid("5fb7fa03-5219-4026-824e-85e6c3fc0776"),
                            Cantidad = 15,
                            Color = "Negro",
                            Descripcion = "Chaqueta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Chaqueta",
                            ParaSexo = "Masculino",
                            Referencia = "C3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/C3.png",
                            Valor = 140000
                        },
                        new
                        {
                            IdProducto = new Guid("b961e5a0-fa58-4240-a635-7c4b16e1f1f0"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Medias",
                            EsDeLosMasBuscados = true,
                            Nombre = "Medias",
                            ParaSexo = "Masculino",
                            Referencia = "M3",
                            Talla = "5",
                            UrlImagen = "ProductosImagenes/M3.png",
                            Valor = 3000
                        },
                        new
                        {
                            IdProducto = new Guid("b91d12a9-117f-464f-a478-7730ed36a9ed"),
                            Cantidad = 15,
                            Color = "Blanco y rojo",
                            Descripcion = "Falda larga",
                            EsDeLosMasBuscados = true,
                            Nombre = "Falda larga",
                            ParaSexo = "Femenino",
                            Referencia = "FL3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/FL3.png",
                            Valor = 35000
                        },
                        new
                        {
                            IdProducto = new Guid("b041f1e9-6935-4c49-b5c8-6029bede1b87"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Camiseta corta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta",
                            ParaSexo = "Femenino",
                            Referencia = "CA5",
                            Talla = "16",
                            UrlImagen = "ProductosImagenes/CA5.png",
                            Valor = 45000
                        });
                });

            modelBuilder.Entity("LionDev.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDeDocumento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("39cf0156-5037-49c9-a776-79ab5eeb8acf"),
                            Apellidos = "Falcao",
                            Contrasena = "Rada1",
                            CorreoElectronico = "rada@gmail.com",
                            Direccion = "Calle 1",
                            Genero = "Masculino",
                            Nombres = "Radamel",
                            NumeroDeDocumento = "12345",
                            Rol = "Comprador",
                            TipoDeDocumento = "Cedula"
                        },
                        new
                        {
                            IdUsuario = new Guid("d6707a61-1c71-4eff-93e1-71431534c721"),
                            Apellidos = "Rodriguez",
                            Contrasena = "James1",
                            CorreoElectronico = "james@gmail.com",
                            Direccion = "Calle 2",
                            Genero = "Masculino",
                            Nombres = "James",
                            NumeroDeDocumento = "12346",
                            Rol = "Administrador",
                            TipoDeDocumento = "Cedula"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
